---

- name: Install k3s dashboard
  command: >-
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended/kubernetes-dashboard.yaml
  changed_when: true
