---

- name: Install k3s dashboard
  command: >-
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
  changed_when: true

- name: Apply dashboard ingress config
  command: >-
    kubectl apply -f dashboardIngress.yaml
  changed_when: true
