name: "Terraform"

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: terraform-setup
        uses: hashicorp/setup-terraform@v2

      - id: init
        run: terraform init -no-color

      - id: plan
        run: terraform plan -no-color

      - id: apply
        run: terraform apply -no-color -auto-approve -input=false

      - id: output
        run: terraform output -no-color -json

      - id: print_output
        run: echo "${{ steps.output.outputs.stdout }}"

      - id: terraform destroy
        if: ${{ always() }}
        run: terraform destroy -no-color -auto-approve -input=false
