name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hashicorp/setup-terraform@v2

      - id: init
        run: terraform init

      - id: plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}

      - id: apply
        run: terraform apply -auto-approve -input=false

      - id: destroy
        run: terraform destroy -auto-approve -input=false
