name: "Terraform"

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: terraform-setup
        uses: hashicorp/setup-terraform@v2

      - id: init
        run: terraform init -no-color

      - id: plan
        run: terraform plan -no-color

      - id: apply
        run: terraform apply -no-color -auto-approve -input=false

      - id: output
        run: terraform output -no-color -json

      - id: print-and-save-output
        run: |
          mkdir build
          echo "${{ steps.output.outputs.stdout }}" | tee build/terraformOut.json

      - id: setup-yq
        uses: mikefarah/yq@v4.33.2

      # TODO: Turn controllerIps into a list like nodeIps
      # TODO: Add node names to ansible config
      # TODO: Move generated hosts.ini to build/
      - id: host-template
        run: |
          export CONTROLLER_IPS=$(cat ansible/terraformOut.json | yq '.controller_ip_addr.value as $ip | $ip')
          export NODE_IPS=$(cat ansible/terraformOut.json | yq '.node_ip_addr.value[] as $ips | $ips')
          echo $CONTROLLER_IPS
          echo $NODE_IPS
          cat ansible/hosts-template.ini | envsubst '${CONTROLLER_IPS} ${NODE_IPS}' > ansible/hosts.ini
          cat ansible/hosts.ini

#      - id: terraform-destroy
#        if: ${{ always() }}
#        run: terraform destroy -no-color -auto-approve -input=false
