name: "Terraform"

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - id: checkout
        uses: actions/checkout@v3

      - id: terraform-setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false # Disable the wrapper, as it conflicts with output capture

      - id: init
        run: terraform init -no-color

      # The binary terraform-bin must be used when capturing output and the terraform_wrapper is enabled
      - id: plan
        run: terraform-bin plan -no-color

      - id: apply
        run: terraform apply -no-color -auto-approve -input=false

      - run: echo ${{ steps.apply.outputs.stdout }}
      - run: echo ${{ steps.apply.outputs.stderr }}
      - run: echo ${{ steps.apply.outputs.exitcode }}
      - run: echo ${{ steps.apply.outputs.instance_ip_addr }}

      - id: destroy
        if: ${{ always() }}
        run: terraform destroy -no-color -auto-approve -input=false
